# Generated by Django 2.1 on 2019-08-15 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('federal', '0002_ejemplar'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetallePrestamo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaprestamo', models.DateField()),
                ('nombrecliente', models.CharField(max_length=45)),
                ('telefonocliente', models.CharField(max_length=45)),
                ('estado', models.BooleanField()),
            ],
        ),
        migrations.RenameField(
            model_name='ejemplar',
            old_name='libro',
            new_name='Libro',
        ),
        migrations.AlterField(
            model_name='ejemplar',
            name='fechadecompra',
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name='detalleprestamo',
            name='Ejemplar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='federal.Ejemplar'),
        ),
        migrations.AddField(
            model_name='detalleprestamo',
            name='Prestamo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='federal.Prestamo'),
        ),
    ]
