# Generated by Django 2.1 on 2019-08-15 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federal', '0003_auto_20190815_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='copias',
            field=models.IntegerField(default=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fechaprestamo',
            field=models.DateField(verbose_name='Fecha de Prestamo'),
        ),
    ]
