# Generated by Django 2.1 on 2019-08-15 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federal', '0004_auto_20190815_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='copias',
            field=models.IntegerField(null=True),
        ),
    ]
